# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7623874b70c7631dbac2e09338bcf89ed3ada973dbd35be27fe4100507cd82bee96f196ddef4966487865775caf645b45b85b37cbabda89333179dca5a32f066

test:
  secret_key_base: 46a78db655b25f27a7f3c30a901bab6a060d7fa64089ffd3c8d6aa43d24bc1d3db53bd709775c721553f9f66c8d9a113e08eb2cb6d5e385f8b528ccec5a86712

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
